// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEBzvSyv1WwhPj-pL1Jm_Y5BkHsji7w3I',
    appId: '1:582659952360:web:bcf7a56e067dde34f4035d',
    messagingSenderId: '582659952360',
    projectId: 'fish-37efe',
    authDomain: 'fish-37efe.firebaseapp.com',
    storageBucket: 'fish-37efe.appspot.com',
    measurementId: 'G-DZ1THWHDXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArDb85fjLnGvwvzUWggnoXfYMvq6AntdI',
    appId: '1:582659952360:android:82a2d0f08933e0dcf4035d',
    messagingSenderId: '582659952360',
    projectId: 'fish-37efe',
    storageBucket: 'fish-37efe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6xoY8IWedHUj77UVcoW1_rgzHhGVCowM',
    appId: '1:582659952360:ios:51161dce4a83a356f4035d',
    messagingSenderId: '582659952360',
    projectId: 'fish-37efe',
    storageBucket: 'fish-37efe.appspot.com',
    iosClientId: '582659952360-pe031tgk4dq1s0m7l9tvm4qqrgp29vsv.apps.googleusercontent.com',
    iosBundleId: 'com.testing.sam',
  );
}
